import { Category, Phrase } from './types';
import { Colors } from '../theme';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'self-love',
    name: 'Self-Love',
    icon: 'favorite',
    colorLight: Colors.category.selfLove.light,
    colorDark: Colors.category.selfLove.dark,
    iconColor: Colors.category.selfLove.icon,
    gradients: ['#fef2f2', '#fecdd3', '#fda4af'],
  },
  {
    id: 'growth',
    name: 'Growth',
    icon: 'eco',
    colorLight: Colors.category.growth.light,
    colorDark: Colors.category.growth.dark,
    iconColor: Colors.category.growth.icon,
    gradients: ['#ecfdf5', '#a7f3d0', '#6ee7b7'],
  },
  {
    id: 'calm',
    name: 'Calm',
    icon: 'air',
    colorLight: Colors.category.calm.light,
    colorDark: Colors.category.calm.dark,
    iconColor: Colors.category.calm.icon,
    gradients: ['#f0f9ff', '#bae6fd', '#7dd3fc'],
  },
  {
    id: 'focus',
    name: 'Focus',
    icon: 'wb-sunny',
    colorLight: Colors.category.focus.light,
    colorDark: Colors.category.focus.dark,
    iconColor: Colors.category.focus.icon,
    gradients: ['#fefce8', '#fef08a', '#fde047'],
  },
  {
    id: 'confidence',
    name: 'Confidence',
    icon: 'auto-awesome',
    colorLight: Colors.category.confidence.light,
    colorDark: Colors.category.confidence.dark,
    iconColor: Colors.category.confidence.icon,
    gradients: ['#faf5ff', '#e9d5ff', '#d8b4fe'],
  },
  {
    id: 'gratitude',
    name: 'Gratitude',
    icon: 'spa',
    colorLight: Colors.category.gratitude.light,
    colorDark: Colors.category.gratitude.dark,
    iconColor: Colors.category.gratitude.icon,
    gradients: ['#fff7ed', '#fed7aa', '#fdba74'],
  },
];

export const MOCK_PHRASES: Phrase[] = [
  {
    id: '1',
    text: 'The sun will rise and we will try again.',
    author: 'Unknown',
    categoryId: 'self-love',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 1200,
  },
  {
    id: '2',
    text: 'Small steps lead to big destinations.',
    author: 'Unknown',
    categoryId: 'growth',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 842,
  },
  {
    id: '3',
    text: 'The best way to predict the future is to create it.',
    author: 'Peter Drucker',
    categoryId: 'focus',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 2100,
  },
  {
    id: '4',
    text: 'You are worthy of love and belonging.',
    author: 'Brené Brown',
    categoryId: 'self-love',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 3500,
  },
  {
    id: '5',
    text: 'Peace comes from within. Do not seek it without.',
    author: 'Buddha',
    categoryId: 'calm',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 1800,
  },
  {
    id: '6',
    text: 'Believe you can and you are halfway there.',
    author: 'Theodore Roosevelt',
    categoryId: 'confidence',
    createdAt: new Date().toISOString(),
    isActive: true,
    likes: 2800,
  },
];
